services:
  - type: web
    name: doll-collection
    env: node
    buildCommand: npm run install-all && npm run build
    startCommand: npm run server
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 3001
    disk:
      name: data
      mountPath: /opt/render/project/src/server
      sizeGB: 1